-- Create sequences for Oracle
CREATE SEQUENCE user_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE pdf_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE topic_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE quiz_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE study_progress_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE quiz_attempt_id_seq START WITH 1 INCREMENT BY 1;
